version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "amazon-polly-async-batch"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1duncjssyz1q6"
s3_prefix = "amazon-polly-async-batch"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Notifyemail=\"pterjon@amazon.com\""
